### ISSUE TITLE
Some documentation

### ISSUE THREAD

**Issue by Azecko** [Azecko/epfl-email-signatures#13]
README.md is looking a bit empty...

**Comment by ponsfrilus** [comment]
We need 3 types of documentation:
1. README.md with some broad explanations and a screenshot.
2. DOCUMENTATION.md that can be used to generate a PDF for the service desk whenever user want to know how to use a signature in their email client. Maybe it would help to have some basic procedure on how to use the tool with main email clients:  
- Outlook web access
- Outlook (windows + mac if different, maybe 2 or 3 versions)
- [Thunderbird](https://getthunderbird.com)
- Mail
- [mailspring](https://www.getmailspring.com) ?
- ...
3. Documentation integrated to the app (e.g. with some modal or/and popover) that guide users thought usage + explicit explanation on why remote content can be a privacy issue (http://mzl.la/1ApHqTF).
