### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by Azecko** [Azecko/epfl-email-signatures#18]
`EPFL-Signatures` is a bit problematic because of `eSign` from EPFL.

What about `EPFL email Signatures`  ?
And for the GitHub repository, `epfl-email-signatures`

**Comment by ponsfrilus** [comment]
No need to capitalize the "Signatures". `EPFL email signatures` is fine.
Change the repository name too.
At some point, this repository should be in [epfl-si](https://github.com/epfl-si) instead of in a personal repo.
