### ISSUE TITLE
Integration with EPFL other tools / hosting

### ISSUE THREAD

**Issue by ponsfrilus** [Azecko/epfl-email-signatures#49]
As the page is self-contended, it should be hosted on people.epfl.ch/something.
When editing a profile page (on people.epfl.ch), a link to the tools (e.g. people.epfl.ch/something#00000) with auto-filled info should be provided.

**Comment by Azecko** [comment]
The tool is now available on https://people.epfl.ch/signatures/
The PR to add a little href on every people.epfl.ch page has been made. Now we wait, but it should come soon.
